### ISSUE TITLE
Review Log In Process

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.InteractiveBrokers#109]
#### Expected Behavior
Informs users they didn't use the correct credentials.

#### Actual Behavior
We can see that IBAutomater doesn't move past the Log In window:
```
2024-04-29T18:13:48.5741860Z TRACE:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): Click button: [Log In]
2024-04-29T18:15:45.8683713Z TRACE:: MessagingCloud.HasSubscribers: False
2024-04-29T18:28:29.9922351Z TRACE:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): IB launcher log file: /QuantConnect/live/Jts/launcher.log
```

The problem is invalid user name:
```
 Loading IBGateway - Version: 1019 - Path: /QuantConnect/live/ibgateway - User: El Chavo del Ocho
```

when members use their real name instead of the username. E.g.
```
 Loading IBGateway - Version: 1019 - Path: /QuantConnect/live/ibgateway - User: chavito8
```

#### Potential Solution
N/A

#### Reproducing the Problem
Deploy to IB and use your real name as user name.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
😬 seems a little tricky to detect this one reliably.

**Comment by Martin-Molinero** [comment]
When submitting a user name with spaces, the log in button is not even clickable, we could detect this specifically and report it back to the user as an error
<img width="392" alt="image" src="https://github.com/QuantConnect/Lean.Brokerages.InteractiveBrokers/assets/18473240/ee700a0d-68b1-4d5f-b936-fc5a9f8df7d6">

**Comment by tmills86** [comment]
Any invalid characters in the username, including capital letters, will grey out the login box
