### ISSUE TITLE
IBDataDownloader Does Not Download TradeBar

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.InteractiveBrokers#119]
#### Expected Behavior
Be able to download trade bar data with minute resolution:

```
lean data download --data-provider-historical "Interactive Brokers" --data-type Trade --resolution Minute --security-type Equity --ticker NVDA,AMD --market USA --start 20240701 --end 20240724
```

#### Actual Behavior
The LEAN CLI code returns:
> DownloaderDataProvider.Main(): No data available for the following parameters: Symbol:
NVDA RHM8UTD8DT2D, Resolution: Minute, StartUtc: 7/1/2024 12:00:00 AM, EndUtc: 7/24/2024 12:00:00 AM, TickType: Trade

#### Potential Solution
N/A

#### Reproducing the Problem
Use LEAN CLI to download data

#### System Information
LEAN CLI

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean.Brokerages.InteractiveBrokers/pull/120
