### ISSUE TITLE
build fails - Detected package downgrade: QuantConnect.pythonnet from 2.0.42 to 2.0.41

### ISSUE THREAD

**Issue by laur89** [QuantConnect/Lean.Brokerages.InteractiveBrokers#138]
#### Expected Behavior
Project builds via `dotnet build QuantConnect.InteractiveBrokersBrokerage.sln`

#### Actual Behavior
Build fails:
```
    /home/me/Lean.Brokerages.InteractiveBrokers/QuantConnect.InteractiveBrokersBrokerage/QuantConnect.InteractiveBrokersBrokerage.csproj : error NU1605: 
      Warning As Error: Detected package downgrade: QuantConnect.pythonnet from 2.0.42 to 2.0.41. Reference the package directly from the project to select a different version. 
       QuantConnect.Brokerages.InteractiveBrokers -> QuantConnect.Lean.Engine 2.5.16814 -> QuantConnect.Common 1.0.0 -> QuantConnect.pythonnet (>= 2.0.42) 
       QuantConnect.Brokerages.InteractiveBrokers -> QuantConnect.Lean.Engine 2.5.16814 -> QuantConnect.pythonnet (>= 2.0.41)
```

`dotnet nuget why QuantConnect.pythonnet` offender tree is [here](https://gist.github.com/laur89/623e95ca257967a681b4d49d5e0c1a82)

#### Potential Solution

Explicitly adding `<PackageReference Include="QuantConnect.pythonnet" Version="2.0.42" />` pkg ref to `QuantConnect.InteractiveBrokersBrokerage.csproj` solves the error, but unsure whether that's the way to go.

Only references to `2.0.41`:
```sh
$ grep '2\.0\.41' *

./QuantConnect.InteractiveBrokersBrokerage.Tests/obj/project.assets.json:1570:          "QuantConnect.pythonnet": "2.0.41",
./QuantConnect.InteractiveBrokersBrokerage/obj/project.assets.json:331:          "QuantConnect.pythonnet": "2.0.41"
./QuantConnect.InteractiveBrokersBrokerage/obj/project.nuget.cache:35:    "/home/me/.nuget/packages/quantconnect.pythonnet/2.0.41/quantconnect.pythonnet.2.0.41.nupkg.sha512",
```

#### Reproducing the Problem

Run `dotnet build QuantConnect.InteractiveBrokersBrokerage.sln`

#### System Information

Running on debian testing

```sh
$ uname -a
Linux p14s 6.12.5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.5-1 (2024-12-15) x86_64 GNU/Linux
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @laur89! Sorry we don't give local deployments support, please use the [lean cli](https://www.quantconnect.com/docs/v2/lean-cli) or the [local platform](https://www.quantconnect.com/docs/v2/local-platform). That said, you probably need a clean build.
