### ISSUE TITLE
Extends IBDownloader to support all security types.

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.InteractiveBrokers#4]
#### Expected Behavior
`IBDownloader` can fetch data from all securities types.
https://interactivebrokers.github.io/tws-api/historical_data.html

#### Actual Behavior
Only forex is supported.

#### Potential Solution
Extends `IBDownloader` to support all security types.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
This issue has been solved by https://github.com/QuantConnect/Lean.Brokerages.InteractiveBrokers/pull/110. The lean cli data download tool can be used, any historical resolution and asset supported by the brokerage will work.
