### ISSUE TITLE
Stop Limit Order Status

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.InteractiveBrokers#81]
#### Expected Behavior
Stop Limit orders are processed correctly.

#### Actual Behavior
Stop Limit orders are placed, but we don't get a status change from new to submitted:

![capture (2)](https://github.com/QuantConnect/Lean.Brokerages.InteractiveBrokers/assets/6889033/dc831dc4-1d90-4974-a502-a94d605e9c69)

#### Potential Solution
N/A

#### Reproducing the Problem
Deploy the following algorithm to IB Paper:

```python

# region imports
from AlgorithmImports import *
# endregion

class EnergeticOrangeFox(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2022, 9, 14)
        self.equity = self.AddEquity("DLO")
        self.ticket = None

    def OnData(self, data: Slice):
        if self.ticket:
            return

        self.ticket = self.StopLimitOrder(
            self.equity.Symbol, 1, 
            self.equity.Price * 1.10,
            self.equity.Price * 0.90, 
            tag='Entry.StopLimit')

        self.StopMarketOrder(
            self.equity.Symbol, 1,
            self.equity.Price * 1.10, 
            tag='Entry.StopMarket')

        self.LimitOrder(
            self.equity.Symbol, 1,
            self.equity.Price * 0.90, 
            tag='Entry.Limit')
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
We traced this to an issue with IB Gateway API. We reported it to their API team and have not gotten a response.
